Adding zeroteir to jeeves jr
RAD-Development/nix-dotfiles pull request #26
Opened 2024-01-06 22:20 UTC by RichieCahill

2024-01-06 22:44 UTC, DerDennisOP requested changes
remove weired comments

2024-01-06 22:44 UTC, DerDennisOP commented on .gitignore
> +# y?
why those comments?

2024-01-06 22:44 UTC, DerDennisOP commented on systems/jeeves-jr/configuration.nix
> +    zerotierone = {
up to you what you put in your config, but for me personally, isnt there a opensource solution for the same thing or can this be selfhosted?

2024-01-06 22:46 UTC, ahuston-0 commented on .gitignore
> +# y?
not sure if there's a specific reason this is here considering that we have .envrc checked in, but here's the relevant nix docs, its for automatic shell activation based on any shell hooks https://nix.dev/guides/recipes/direnv

2024-01-06 22:47 UTC, DerDennisOP commented on .gitignore
> +# y?
yeah im using this

2024-01-06 22:47 UTC, ahuston-0 commented on .gitignore
> +# y?
if you do `nixos-rebuild test` or other similar command it generates the below artifacts in the current directory as reflections of what the system will build, and they can be useful but we definitely dont want them checked in.

2024-01-06 22:48 UTC, ahuston-0 commented on .gitignore
> +# y?
If you run `nix develop` it will generate pre-commit hooks using the python library precommit ([see here](https://github.com/RAD-Development/nix-dotfiles/blob/main/flake.nix#L65))

2024-01-06 22:49 UTC, ahuston-0 commented on .gitignore
> +# y?
@DerDennisOP would need to comment on if this is necessary anymore

2024-01-06 22:52 UTC, ahuston-0 requested changes
Next time would appreciate if you start a review yourself on the affected lines and not include the question directly in the commit. Not sure I understand the ask, are you trying to remove unneeded things or have us comment the `.gitignore`?

Otherwise looks good

2024-01-06 22:52 UTC, DerDennisOP requested changes

2024-01-06 22:52 UTC, DerDennisOP commented on .gitignore
> +# y?
```suggestion
# direnv
```

2024-01-06 22:52 UTC, DerDennisOP commented on .gitignore
> +# y?
```suggestion
# build outputs
```

2024-01-06 22:52 UTC, ahuston-0 commented on systems/jeeves-jr/configuration.nix
> +    zerotierone = {
It can be self-hosted but its a huge pain sometimes. Its something we are considering eventually but its a lot of commitment

2024-01-06 22:53 UTC, DerDennisOP commented
> Next time would appreciate if you start a review yourself on the affected lines and not include the question directly in the commit. Not sure I understand the ask, are you trying to remove unneeded things or have us comment the `.gitignore`?
> 
> Otherwise looks good

same, also don't merge if It is not fully approved or as I taged alice to doubble check merge #24 wher you justed merged anyway

2024-01-06 22:54 UTC, RichieCahill commented on .gitignore
> +# y?
pleas ask befor telling me to remove next time

2024-01-06 22:56 UTC, DerDennisOP commented on systems/jeeves-jr/configuration.nix
> +    zerotierone = {
would be fun for later. not my config, don't care resolved.

2024-01-06 22:57 UTC, RichieCahill commented on systems/jeeves-jr/configuration.nix
> +    zerotierone = {
zerotier is opensource or source available and i can self host if i need more then 25 devises but i dont yet

2024-01-06 22:59 UTC, RichieCahill commented
> Next time would appreciate if you start a review yourself on the affected lines and not include the question directly in the commit. Not sure I understand the ask, are you trying to remove unneeded things or have us comment the `.gitignore`?
> 
> Otherwise looks good

sorry this is what Phil and I have done it the past.

2024-01-06 23:00 UTC, RichieCahill commented
> > Next time would appreciate if you start a review yourself on the affected lines and not include the question directly in the commit. Not sure I understand the ask, are you trying to remove unneeded things or have us comment the `.gitignore`?
> > Otherwise looks good
> 
> same, also don't merge if It is not fully approved or as I taged alice to doubble check merge #24 wher you justed merged anyway

the merge protection is set to one approval so we need one approval

2024-01-06 23:00 UTC, ahuston-0 commented
> > Next time would appreciate if you start a review yourself on the affected lines and not include the question directly in the commit. Not sure I understand the ask, are you trying to remove unneeded things or have us comment the `.gitignore`?
> > Otherwise looks good
> 
> same, also don't merge if It is not fully approved or as I taged alice to doubble check merge #24 wher you justed merged anyway

Sorry should have put it here but I'm good with doing 1 person approval, if you want to do all approvals required I can set it up but I'm fine with #24 being merged.
https://github.com/RAD-Development/nix-dotfiles/pull/24#issuecomment-1879867241

2024-01-06 23:01 UTC, DerDennisOP commented
> the merge protection is set to one approval so we need one approval

usually one approval is enough, this time I espacially taged alice to approve also

2024-01-06 23:01 UTC, ahuston-0 commented on .gitignore
> +# y?
```suggestion
# nix precommit hooks
```

2024-01-06 23:02 UTC, ahuston-0 commented on .gitignore
> +# y?
Unresolving and giving the comment

2024-01-06 23:03 UTC, ahuston-0 commented
> > the merge protection is set to one approval so we need one approval
> 
> usually one approval is enough, this time I espacially taged alice to approve also

Ah I was doing work so I didn't see it.

2024-01-06 23:04 UTC, ahuston-0 commented on .gitignore
> +# y?
added in 31375274963df8b25b0ad04579c203fdbe6210de

2024-01-06 23:04 UTC, ahuston-0 approved these changes
Looks fine with updated comments. Approved

2024-01-06 23:05 UTC, ahuston-0 commented
Since theres still stuff pending from Dennis, requesting we wait for him as well just in case the other conversations need to get resolved as well.

2024-01-06 23:10 UTC, RichieCahill commented
I cant merge yall both requested changes.
PR etiquette says you should reserved requesting changes for CATASTROPHIC bugs that will break stuff if merged.

2024-01-06 23:14 UTC, ahuston-0 commented
> I cant merge yall both requested changes. PR etiquette says you should reserved requesting changes for CATASTROPHIC bugs that will break stuff if merged.

I'll check that later but also not comfortable merging code with `y?` as the comment

2024-01-06 23:17 UTC, RichieCahill commented
> > I cant merge yall both requested changes. PR etiquette says you should reserved requesting changes for CATASTROPHIC bugs that will break stuff if merged.
> 
> I'll check that later but also not comfortable merging code with `y?` as the comment, so I requested the change.

I get that but you can make a comment without requesting a change

2024-01-07 11:04 UTC, DerDennisOP approved these changes

2024-01-07 21:28 UTC, merged