Add autopull service for testing & pre-commit-hooks
RAD-Development/nix-dotfiles pull request #4
Opened 2023-12-27 06:54 UTC by ahuston-0

Adds an service to pull git repositories (currently setup as a template service in systemd, but not in nix) and allows the service to then trigger the nixos-upgrade service. 

Adds nixpkgs.fmt to the flake config so we can run `nix fmt`

Adds pre-commit-hooks

Signed-off-by: ahuston-0 <aliceghuston@gmail.com>

2023-12-30 17:37 UTC, ahuston-0 commented
Switched from (Cachix's pre-commit-hooks)[https://github.com/cachix/pre-commit-hooks.nix] to (nix-pre-commit)[https://github.com/jmgilman/nix-pre-commit] as the issue I was having with the `sops-nix` hook conflicting doesn't seem to happen there. Currently there is one hook for running `nix fmt` and another for `nix flake check`. Please let me know if this needs more hooks before going to main

2023-12-30 23:54 UTC, DerDennisOP requested changes
everything else looks good

2023-12-30 23:54 UTC, DerDennisOP commented on flake.nix
> +    nix-pre-commit.url = "github:jmgilman/nix-pre-commit";
check with `nix flake metadata`

2023-12-30 23:54 UTC, DerDennisOP commented on flake.nix
> +    nix-pre-commit.url = "github:jmgilman/nix-pre-commit";
```suggestion
    nix-pre-commit = {
      url = "github:jmgilman/nix-pre-commit";
      inputs = {
        nixpkgs.follow = "nixpkgs";
        flake-utils.follow = "flake-utils";
      };
    };
```
try that

2023-12-31 05:21 UTC, ahuston-0 commented on systems/palatine-hill/configuration.nix
> +    autopull = {
as discussed, moving this out.

2023-12-31 06:15 UTC, ahuston-0 commented on systems/palatine-hill/configuration.nix
> +    autopull = {
done with [12500be](https://github.com/RAD-Development/nix-dotfiles/pull/4/commits/12500bee1499961a626862260ac79833e6c1ef75)

2024-01-01 10:02 UTC, DerDennisOP approved these changes

2024-01-01 17:41 UTC, merged